sonar.projectKey=tyrpik_ProjektowanieObiektowe
sonar.organization=tyrpik

sonar.sources=wzorce_behawioralne/frontend,wzorce_behawioralne/backend

sonar.sourceEncoding=UTF-8
sonar.javascript.environments=browser,node