sonar.projectKey=tyrpik_ProjektowanieObiektowe
sonar.organization=tyrpik

sonar.sources=wzorce_behawioralne/frontend,wzorce_behawioralne/backend
sonar.exclusions=Chmura/**,selenium/**

sonar.sourceEncoding=UTF-8
sonar.javascript.environments=browser,node