sonar.projectKey=obiektowe6_tyrpik
sonar.projectName=obiektowe6

sonar.sources=wzorce_behawioralne/frontend,wzorce_behawioralne/backend

sonar.sourceEncoding=UTF-8
sonar.javascript.environments=browser,node