version: '3.8'

services:
  backend-server:
    build: ./backend
    container_name: backend_container
    ports:
      - "3001:3001"
    networks:
      - sklep-network

  frontend-client:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend-server
    networks:
      - sklep-network

networks:
  sklep-network:
    driver: bridge